### ISSUE TITLE
Interstitial AD

### ISSUE THREAD

**Issue by koljanich** [OrigameStudio/admob-unity-plugin#13]
This is great Plug-In! Easy to start and great work! But how I could load and show the Interstitial AdMob?

**Comment by koljanich** [comment]
Anybody home?

**Comment by guillermocalvo** [comment]
Hi, interstitial ads are not supported. Currently I don't have time to work on it, but you can use the source code and implement that for your games.

**Comment by AntonyKapustin** [comment]
is anybody find solution for interstitial?

**Comment by guillermocalvo** [comment]
I haven't had time to work on this new feature yet. Please feel free to fork and submit pull requests.

**Comment by AntonyKapustin** [comment]
Is anyone created fork with interstitial ads?

**Comment by ghost** [comment]
I added a upgraded version https://github.com/unity-plugins/Unity-Admob ,support interstitial

**Comment by mandalaku** [comment]
Hi. Unity-plugin
Can you please add location targeting
