### ISSUE TITLE
Mockup banner is showing, but real in build app is not

### ISSUE THREAD

**Issue by stoil2** [OrigameStudio/admob-unity-plugin#15]
Hello,

I added the prefab to my scene, attached the scripts, and the mockup banner is showing OK. But when I built the app and deploy on phone, nothing is showing. I added my admob app id to the prefab. Also in debug mode using the debug script only the mockup ads are showing, real ones don't show.
What could be wrong? Does it matter what are the coordinates of the prefab in the scene?

**Comment by guillermocalvo** [comment]
Hi,

The coordinates of the prefab doesn't matter at all.
- Make sure test mode is disabled
- loadOnStart is enabled
- check your publisher ID
- try as many different devices as you can

Hope that works.

**Comment by stoil2** [comment]
Hi,

thank you, it is working now. Issue was with the publisher ID.

Best regards,
Stoil
