### ISSUE TITLE
Invalid ad request.

### ISSUE THREAD

**Issue by lhes** [OrigameStudio/admob-unity-plugin#4]
I followed the instructions - gave the publisher id, made sure test id and guess device id were checked. Built and installed and i get this error. Next I got the device id (wasn't sure, used DeviceId by redphx on play store) and used it but get the same error. Help?

**Comment by gerrold** [comment]
The same problem is present in my case. Here is a screenshot from the game:

https://www.dropbox.com/s/69sa0l8tmqu219j/2014-03-18%2021.28.01.png

and here are the settings from Unity:

https://www.dropbox.com/s/5mxnm5cklgike5h/Clipboard01.jpg

**Comment by gerrold** [comment]
so, a quick update: the bug happens only with leaderboard. Ihes, try to change to banner type
